cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'ack'
brew 'autojump'
brew 'chruby'
brew 'coreutils'
brew 'direnv'
brew 'emacs-plus'
brew 'elixir'
brew 'erlang'
brew 'git-extras'
brew 'grc'
brew 'imagemagick'
brew 'jq'
brew 'leiningen'
brew 'libgit2'
brew 'openssl'
brew 'macvim'
brew 'memcached'
brew 'mysql'
brew 'nginx'
brew 'node'
brew 'readline'
brew 'reattach-to-user-namespace'
brew 'postgresql'
brew 'rabbitmq'
brew 'readline'
brew 'ruby-install'
brew 'spaceman-diff'
brew 'the_platinum_searcher'
brew 'the_silver_searcher'
brew 'tmux'
brew 'unrar'
brew 'wget'
brew 'yarn'

cask '1password'
cask 'alfred'
cask 'divvy'
cask 'firefox'
cask 'google-chrome'
cask 'slack'
cask 'iterm2'
cask 'sequel-pro'
